### PR TITLE
Clang Tidy addition

### PR DESCRIPTION
**Pull request by bhargav-umd**

### CODE REVIEW

**Comment by shivaang12** [comment]
@bhargav-umd Is this thing related to any article?

**Comment by bhargav-1** [comment]
Its personal experience, cannot be learned anywhere online.

**Comment by bhargav-umd** [comment]
It's based on personal experience in interviews, got to know by the hard way.
Needs to be known to any robotics software developer who has robotics/mechanical background, its obvious for most of the experienced software developers. Clang-Tidy errors/warnings would be the first thing to be noticed once you submit your working coding challenge, few examples include the usage of const, & reference which could be missed while developing.

**Comment by bhargav-umd** [comment]
https://blog.kitware.com/static-checks-with-cmake-cdash-iwyu-clang-tidy-lwyu-cpplint-and-cppcheck/

**Pull request merged**
